### ISSUE TITLE
表单 Schema

### ISSUE THREAD

**Issue by ruibaby** [halo-sigs/plugin-alioss#1]
```yaml
- $formkit: text
  name: bucket
  label: Bucket
  validation: required
- $formkit: text
  name: endpoint
  label: EndPoint
  validation: required
- $formkit: text
  name: access_key
  label: Access Key
  validation: required
- $formkit: text
  name: access_secret
  label: Access Secret
  validation: required
- $formkit: text
  name: location
  label: 上传目录
  placeholder: 如不填写，则默认上传到根目录
- $formkit: select
  name: bind_domain_protocol
  label: 绑定域名协议
  options:
    - label: HTTPS
      value: https
    - label: HTTP
      value: http
- $formkit: text
  name: bind_domain
  label: 绑定域名
  placeholder: 如不设置，那么将使用 Bucket + EndPoint 作为域名
- $formkit: textarea
  name: allow_extensions
  label: 允许上传的文件类型
  placeholder: 使用半角逗号分隔

```
